<a href="https://colab.research.google.com/github/deep3040/TRINIT_ENEMIESOFSYNTAXX_ML/blob/main/final_ml_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_excel("/content/region_crop.xlsx")

In [3]:
df.head()

         STATE  Region_C      SOIL
0  Maharashtra         6   Aluvial
1  Maharashtra         1     Black
2  Maharashtra         2       Red
3  Maharashtra         4  Laterite
4       Kerela         6   Aluvial

In [4]:
le = preprocessing.LabelEncoder()
x1 = df["SOIL"]
y1 = df["STATE"]
x = le.fit_transform(x1)
y = le.fit_transform(y1)
df1 = df.merge(pd.DataFrame({'SOIL_C':x,'STATE_C':y}),right_index=True,left_index = True)
df1.head()

         STATE  Region_C      SOIL  SOIL_C  STATE_C
0  Maharashtra         6   Aluvial       0        2
1  Maharashtra         1     Black       1        2
2  Maharashtra         2       Red       5        2
3  Maharashtra         4  Laterite       3        2
4       Kerela         6   Aluvial       0        1

In [5]:
Region_dict = {1 : "North", 2: "West", 3 : "South", 4 : "East", 5 : "Central", 6 : "Coastal"}
print(Region_dict)

{1: 'North', 2: 'West', 3: 'South', 4: 'East', 5: 'Central', 6: 'Coastal'}

In [6]:
state = input("Enter State : ")
region = int(input("Enter Regional Code (1-6) : "))

Enter State : Sikkim
Enter Regional Code (1-6) : 2

In [69]:
print("For State : {} and Region : {}".format(state,region))
ordinary=df1.query('STATE == @state and Region_C == @region')
reg_soil=ordinary[['STATE_C','SOIL_C']].values #input for classifier
soil_list = list(ordinary['SOIL_C'].values)
#output for state and region
soil_type=ordinary[['SOIL']].values
print("Soil Types found are : \n",soil_type)

For State : Sikkim and Region : 2
Soil Types found are :
 [['Aluvial']
 ['Desert']]

In [10]:
basic=pd.read_excel('/content/season_crop.xlsx')

In [11]:
basic.head()

,SOIL,SEASON,STATE,Rice,Cotton,Sugarcane,Wheat,Millets,Cardamom,Ginger,Coconut,Orange,Soyabean,Maize
0,Aluvial,Rabi,Maharashtra,0,0,0,1,0,0,0,0,0,0,0
1,Black,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0
2,Red,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0
3,Laterite,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0
4,Mountain,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0

In [33]:
le2 = preprocessing.LabelEncoder()
x2 = basic["SOIL"]
y2 = basic["STATE"]
z2 = basic["SEASON"]
a = le2.fit_transform(x2)
b = le2.fit_transform(y2)
c= le2.fit_transform(z2)
basic1 = basic.merge(pd.DataFrame({'SOIL_C':a,'STATE_C':b,'SEASON_C':c}),right_index=True,left_index = True)
basic1.head()

,SOIL,SEASON,STATE,Rice,Cotton,Sugarcane,Wheat,Millets,Cardamom,Ginger,Coconut,Orange,Soyabean,Maize,SOIL_C,STATE_C,SEASON_C
0,Aluvial,Rabi,Maharashtra,0,0,0,1,0,0,0,0,0,0,0,0,2,1
1,Black,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0,1,2,1
2,Red,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0,5,2,1
3,Laterite,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0,3,2,1
4,Mountain,Rabi,Maharashtra,0,0,0,0,0,0,0,0,0,0,0,4,2,1

In [34]:
X = basic1[['STATE_C','SOIL_C','SEASON_C']]
Y = basic1[['Rice','Cotton','Sugarcane','Wheat','Millets','Cardamom','Ginger','Coconut','Orange','Soyabean','Maize']]

In [35]:
classifier = DecisionTreeClassifier()
classifier.fit(X,Y)

DecisionTreeClassifier()

In [77]:
season = int(input("Enter Season : "))
if state == "Jammu and Kashmir" :
  st = 0
elif state == "Kerala" :
  st = 1
elif state == "Maharashtra" : 
  st = 2
elif state == "Sikkim" : 
  st = 3
elif state == "Uttarakhand" : 
  st = 4
pred_list = np.insert(reg_soil, 2, season, axis = 1)

Enter Season : 0

In [90]:
crop_pred = classifier.predict(pred_list)
crop_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [91]:
rice_predict_yeild = ""
rice_predict_profit = ""
rice_predict_cost =  ""
cotton_predict_yeild = ""
cotton_predict_profit = ""    
cotton_predict_cost = ""
sugarcane_predict_yeild = ""
sugarcane_predict_profit = ""
sugarcane_predict_cost = ""
wheat_predict_yeild = ""
wheat_predict_profit = ""
wheat_predict_cost = ""
millets_predict_yeild = ""
millets_predict_profit = ""
millets_predict_cost = ""
carda_predict_yeild = ""
carda_predict_profit = ""
carda_predict_cost =""
gin_predict_yeild =""
gin_predict_profit =""
gin_predict_cost =""
coco_predict_yeild =""
coco_predict_profit =""
coco_predict_cost =""
orange_predict_yeild =""
orange_predict_profit =""
orange_predict_cost =""
soya_predict_yeild =""
soya_predict_profit =""
soya_predict_cost =""
mai_predict_yeild =""
mai_predict_profit =""
mai_predict_cost = ""

In [157]:
result = {"crop" : [], "Profit" : []}

In [158]:
for i in range(len(crop_pred)):
  for j in range(11):
    if crop_pred[i][j]:
      if j == 0:
        print("Rice")
        crop="Rice"
        result["crop"].append("Rice")
        data = pd.read_excel('/content/cropdata.xlsx')
        data1=data.query('STATE == @state and CROP == @crop')
        regressor=LinearRegression()
        X=data1[['YEAR']]
        Y=data1['YEILD']
        Z=data1['PROFIT']
        W=data1['COST OF CULTIVATION']
        #predection of yeild
        regressor.fit(X,Y)
        #a1=regressor.score(X,Y)*100
        rice_predict_yeild = regressor.predict([[2018]])
        #predection of profit
        regressor.fit(X,Z)
        #b1=regressor.score(X,Z)*100
        rice_predict_profit = regressor.predict([[2018]])
        #prediction of cost of cultivation
        regressor.fit(X,W)
        #c1=regressor.score(X,W)*100
        rice_predict_cost = regressor.predict([[2018]])
      elif j == 1:
        print("Cotton")
        crop="Cotton"
        result["crop"].append("Cotton")
        data = pd.read_excel('/content/cropdata.xlsx')
        data2=data.query('STATE == @state and CROP == @crop')
        regressor=LinearRegression()
        X=data2[['YEAR']]
        Y=data2['YEILD']
        Z=data2['PROFIT']
        W=data2['COST OF CULTIVATION']
        #prediction of the yeild
        regressor.fit(X,Y)
        cotton_predict_yeild = regressor.predict([[2018]])
        #prediction of the profit
        regressor.fit(X,Z)
        cotton_predict_profit = regressor.predict([[2018]])
        #prediction of cost of cultivation
        regressor.fit(X,W)
        cotton_predict_cost = regressor.predict([[2018]])
      elif j == 2:
            print("Sugarcane")
            crop="Sugarcane"
            result["crop"]="Rice"
            data = pd.read_excel('/content/cropdata.xlsx')
            data3=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data3[['YEAR']]
            Y=data3['YEILD']
            Z=data3['PROFIT']
            W=data3['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            sugarcane_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            sugarcane_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            sugarcane_predict_cost = regressor.predict([[2018]])
      elif j == 3:
            print("Wheat")
            crop="Wheat"
            result["crop"].append("Wheat")
            data = pd.read_excel('/content/cropdata.xlsx')
            data4=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data4[['YEAR']]
            Y=data4['YEILD']
            Z=data4['PROFIT']
            W=data4['COST OF CULTIVATION']
            #prediction of yeild
            regressor.fit(X,Y)
            wheat_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            wheat_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            wheat_predict_cost = regressor.predict([[2018]])
      elif j == 4:
            print("Millets")
            crop="Millets"
            result["crop"].append("Millets")
            data = pd.read_excel('/content/cropdata.xlsx')
            data5=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data5[['YEAR']]
            Y=data5['YEILD']
            Z=data5['PROFIT']
            W=data5['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            millets_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            millets_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            millets_predict_cost = regressor.predict([[2018]])
      elif j == 5:
            print("Cardamom")
            crop="Cardamom"
            result["crop"].append("Cardamom")
            data = pd.read_excel('/content/cropdata.xlsx')
            data6=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data6[['YEAR']]
            Y=data6['YEILD']
            Z=data6['PROFIT']
            W=data6['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            carda_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            carda_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            carda_predict_cost = regressor.predict([[2018]])
      elif j == 6:
            print("Ginger")
            crop="Ginger"
            result["crop"].append("Ginger")
            data = pd.read_excel('/content/cropdata.xlsx')
            data7=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data7[['YEAR']]
            Y=data7['YEILD']
            Z=data7['PROFIT']
            W=data7['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            gin_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            gin_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            gin_predict_cost = regressor.predict([[2018]])
      elif j == 7:
            print("Coconut")
            crop="Coconut"
            result["crop"].append("Coconut")
            data = pd.read_excel('/content/cropdata.xlsx')
            data8=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data8[['YEAR']]
            Y=data8['YEILD']
            Z=data8['PROFIT']
            W=data8['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            coco_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            coco_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            coco_predict_cost = regressor.predict([[2018]])
      elif j == 8:
            print("Orange")
            crop="Orange"
            result["crop"].append("Orange")
            data = pd.read_excel('/content/cropdata.xlsx')
            data9=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data9[['YEAR']]
            Y=data9['YEILD']
            Z=data9['PROFIT']
            W=data9['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            orange_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            orange_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            orange_predict_cost = regressor.predict([[2018]])
      elif j == 9:
            print("Soyabean")
            crop="Soyabean"
            result["crop"].append("Soyabean")
            data = pd.read_excel('/content/cropdata.xlsx')
            data10=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data10[['YEAR']]
            Y=data10['YEILD']
            Z=data10['PROFIT']
            W=data10['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            soya_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            soya_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            soya_predict_cost = regressor.predict([[2018]])
      elif j == 10:
            print("Maize")
            crop="Maize"
            result["crop"].append("Maize")
            data = pd.read_excel('/content/cropdata.xlsx')
            data11=data.query('STATE == @state and CROP == @crop')
            regressor=LinearRegression()
            X=data11[['YEAR']]
            Y=data11['YEILD']
            Z=data11['PROFIT']
            W=data11['COST OF CULTIVATION']
            #prediction of the yeild
            regressor.fit(X,Y)
            mai_predict_yeild = regressor.predict([[2018]])
            #prediction of the profit
            regressor.fit(X,Z)
            mai_predict_profit = regressor.predict([[2018]])
            #prediction of cost of cultivation
            regressor.fit(X,W)
            mai_predict_cost = regressor.predict([[2018]])

Rice
Cardamom

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [159]:
#diplaying the prediction data (for RICE)
if rice_predict_yeild != "" :
    print(rice_predict_yeild)
if rice_predict_profit != "" :
    print(rice_predict_profit)
    result["Profit"].append(int(rice_predict_profit))
if rice_predict_cost !="" :
    print(rice_predict_cost)

    
#displaying the prediction data (for COTTON)
if cotton_predict_yeild != "" :
    print(cotton_predict_yeild)
if cotton_predict_profit != "":
    print(cotton_predict_profit)
    result["Profit"].append(int(cotton_predict_profit))
if cotton_predict_cost != "":
    print(cotton_predict_cost)

#diplaying the prediction data (for SUGARCANE)
if sugarcane_predict_yeild != "":
    print(sugarcane_predict_yeild)
if sugarcane_predict_profit !="":
    print(sugarcane_predict_profit)
    result["Profit"].append(int(sugarcane_predict_profit))
if sugarcane_predict_cost != "":
    print(sugarcane_predict_cost)

#displaying prediction data (for WHEAT)
if wheat_predict_yeild != "":
    print(wheat_predict_yeild)
if wheat_predict_profit !="":
    print(wheat_predict_profit)
    result["Profit"].append(int(wheat_predict_profit))
if wheat_predict_cost != "":
    print(wheat_predict_cost)

#displaying prediction data(for MILLETS)
if millets_predict_yeild != "":
    print(millets_predict_yeild)
if millets_predict_profit !="":
    print(millets_predict_profit)
    result["Profit"].append(int(millets_predict_profit))
if millets_predict_cost != "":
    print(millets_predict_cost)
    

#displaying prediction data(for CARDAMOM)
if carda_predict_yeild != "":
    print(carda_predict_yeild)
if carda_predict_profit !="":
    print(carda_predict_profit)
    result["Profit"].append(int(carda_predict_profit))
if carda_predict_cost != "":
    print(carda_predict_cost)

#displaying prediction data(for GINGER)
if gin_predict_yeild != "":
    print(gin_predict_yeild)
if gin_predict_profit !="":
    print(gin_predict_profit)
    result["Profit"].append(int(gin_predict_profit))
if gin_predict_cost != "":
    print(gin_predict_cost)
    
#displaying prediction data(for COCONUT)
if coco_predict_yeild != "":
    print(coco_predict_yeild)
if coco_predict_profit !="":
    print(coco_predict_profit)
    result["Profit"].append(int(coco_predict_profit))
if coco_predict_cost != "":
    print(coco_predict_cost)

#displaying prediction data(for ORANGE)
if orange_predict_yeild != "":
    print(orange_predict_yeild)
if orange_predict_profit !="":
    print(orange_predict_profit)
    result["Profit"].append(int(orange_predict_profit))
if orange_predict_cost != "":
    print(orange_predict_cost)
    
#displaying prediction data(for SOYABEAN)
if soya_predict_yeild != "":
    print(soya_predict_yeild)
if soya_predict_profit !="":
    print(soya_predict_profit)
    result["Profit"].append(int(soya_predict_profit))
if soya_predict_cost != "":
    print(soya_predict_cost)
    
#displaying prediction data(for MAIZE)
if mai_predict_yeild != "":
    print(mai_predict_yeild)
if mai_predict_profit !="":
    print(mai_predict_profit)
    result["Profit"].append(int(mai_predict_profit))
if mai_predict_cost != "":
    print(mai_predict_cost)

[3.35]
[11012.]
[19490.]
[3.75]
[16345.]
[6762.]

<ipython-input-159-6c9c37ec8ee7>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if rice_predict_yeild != "" :
<ipython-input-159-6c9c37ec8ee7>:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if rice_predict_profit != "" :
<ipython-input-159-6c9c37ec8ee7>:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if rice_predict_cost !="" :
<ipython-input-159-6c9c37ec8ee7>:49: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if carda_predict_yeild != "":
<ipython-input-159-6c9c37ec8ee7>:51: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if carda_predict_profit !="":
<ipython-input-159-6c9c37ec8ee7>:54: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if carda_predict_cost != "":

In [164]:
result

{'crop': ['Rice', 'Cardamom'], 'Profit': [11012, 16345]}